type User {
  id: String
  email: String
  password: String
}

type Query {
  users: [User]
  login(infos: UserLogin!): LoginInfo
  checkToken: Boolean
}

type Mutation {
  register(infos: UserRegister!): User
}

input UserLogin {
  email: String!
  password: String!
}

input UserRegister {
  email: String!
  password: String!
}
type LoginInfo {
  token: String
  email: String
}
